name: Build Vim Configuration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Vim and Dependencies
      run: |
        pacman -Sy --noconfirm vim git cmake python base-devel jdk-openjdk
    - name: Create Non-root User
      run: |
        useradd -m vimuser
    - name: Setup Vim Configuration
      run: |
        mkdir -p /home/vimuser/.vim
        cp -r .vim/* /home/vimuser/.vim/
        chown -R vimuser:vimuser /home/vimuser/.vim
    - name: Install Vim Plugins
      run: |
        su vimuser -c "vim +'PlugInstall --sync' +qall -E"
    - name: Create Archive
      run: tar -czf vim-config-archlinux.tar.gz -C /home/vimuser/ .vim
