name: Build Vim Configuration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Vim and Dependencies
      run: |
        pacman -Sy --noconfirm vim git
    - name: Setup Vim Configuration
      run: |
        mkdir -p ~/.vim
        cp -r .vim/* ~/.vim/
    - name: Install Vim Plugins
      run: vim +PlugInstall +qall
    - name: Create Archive
      run: tar -czf vim-config-archlinux.tar.gz ~/.vim ~/.vimrc

  build-centos:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: Install Vim and Dependencies
      run: |
        yum install -y vim git
    - name: Setup Vim Configuration
      run: |
        mkdir -p ~/.vim
        cp -r .vim/* ~/.vim/
    - name: Install Vim Plugins
      run: vim +PlugInstall +qall
    - name: Create Archive
      run: tar -czf vim-config-c7-64.tar.gz ~/.vim ~/.vimrc

